## Vectors Assignment - Sri Das

In [1]:
import numpy as np
import pandas as pd

### 1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
lst = [12.23,13.32,100,36.32]
arr = np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32]


### 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
a = np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [4]:
a = np.zeros(10)
print(a)
a[5] = 11
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


### 4. Write a NumPy program to create an array with values ranging from 12 to 38.

In [5]:
a = np.arange(12, 38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


### 5. Write a NumPy program to reverse an array (first element becomes last).

In [6]:
rev_arr = a[::-1]
print(rev_arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


### 6. Write a NumPy program to convert an array to a float type. 

In [7]:
a=np.array([1,2,3,4])
print(a)
farr = np.asfarray(a)
print(farr)

[1 2 3 4]
[1. 2. 3. 4.]


### 7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [8]:
one_arr = np.ones((7,7))
print(one_arr,'\n') 
one_arr[1:-1, 1:-1] = 0
print(one_arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### 8. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [9]:
arr = np.ones((5,5))
print(arr,'\n')
arr_pad=np.pad(arr,pad_width=1, mode='constant', constant_values=0 )
print(arr_pad)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
arr = np.zeros((8,8))
print(arr, '\n')
arr[1::2, ::2] = 1
arr[::2, 1::2] =1
print(arr,'\n')

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]] 



### 10. Write a NumPy program to convert a list and tuple into arrays.

In [11]:
lst=[1,2,3,4,5,6,7,8]
lst_arr = np.array(lst)
print(lst_arr,'\n')
tup = ([8,4,6],[1,2,3])
tup_arr = np.asarray(tup)
print(tup_arr)

[1 2 3 4 5 6 7 8] 

[[8 4 6]
 [1 2 3]]


### 11. Write a NumPy program to append values to the end of an array.

In [12]:
arr=np.array([10,20,30])
np.append(arr, [[40,50,60],[70,80,90]])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### 12. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [13]:
cent=np.array([12, 17.5, 23, 36, 40])
far = ((9*cent)/5) + 32 
print(" Temperature in C:",cent,'\n',"Temperature in F:",far)

 Temperature in C: [12.  17.5 23.  36.  40. ] 
 Temperature in F: [ 53.6  63.5  73.4  96.8 104. ]


### 13. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements 

In [14]:
a = np.array([1,2,3,4,9])
print(len(a))
print(a.itemsize)
print(a.nbytes)

5
8
40


### 14. Write a NumPy program to find common values between two arrays.

In [15]:
arr1 = np.array([1,6,10,34,56])
arr2 = np.array([4,6,34,1,78,17])
print(np.intersect1d(arr1,arr2))

[ 1  6 34]


### 15. Write a NumPy program to get the unique elements of an array.

In [16]:
a = np.array([10,10,20,20,30,30])
print(np.unique(a))
b=np.array([[1,1],[2,3]])
print(np.unique(b))


[10 20 30]
[1 2 3]


### 16. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [17]:
a = np.array([0,10,20,40,60,80])
b = np.array([10, 30, 40, 50, 70])
print(np.setdiff1d(a,b))

[ 0 20 60 80]


### 17. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [18]:
a = np.array([0,10,20,40,60,80])
b = np.array([10, 30, 40, 50, 70])
print(np.setxor1d(a,b))

[ 0 20 30 50 60 70 80]


### 18. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [19]:
a = np.array([0,10,20,40,60,80])
b = np.array([10, 30, 40, 50, 70])
print(np.union1d(a,b))

[ 0 10 20 30 40 50 60 70 80]


### 19. Write a NumPy program to test whether all elements in an array evaluate to True. Note: 0 evaluates to False in python.

In [20]:
print(np.all([[True, False], [True, True]]))
print(np.all([[True, True], [True, True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


### 20. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [21]:
a = np.array([1,2,3,4,5,6])
print(np.argmax(a))
print(np.argmin(a))

5
0


### 21. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [22]:
a = np.array([[0,10,20], [20,30,40]])
print('Values greater than 10:',a[a>10])
print('Indices of values greater than 10:',np.where(a>10))

Values greater than 10: [20 20 30 40]
Indices of values greater than 10: (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


### 22. Write a NumPy program to create an array of ones of size 2 and an array of zeros of size 2.

In [23]:
ones = np.ones(2)
print(ones)
zeros=np.zeros(2)
print(zeros)

[1. 1.]
[0. 0.]


### 23. Write a NumPy program to create a contiguous flattened array.

In [24]:
x = np.array([[10,20,30],[20,40,50]])
np.ravel(x)

array([10, 20, 30, 20, 40, 50])

### 24. Write a NumPy program to create a new shape to an array without changing its data.

In [25]:
a = np.array([[1,2],[3,4],[5,6]])
np.reshape(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

### 25. Write a NumPy program to change the data type of an array.

In [26]:
a = np.array([1,2,3,4,5,6])
print(a.dtype)
a.astype(float)

int64


array([1., 2., 3., 4., 5., 6.])

### 26. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.


In [27]:
loga = np.logspace(2,5,num=20, endpoint=False)
print(loga)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


### 27. Write a NumPy program to concatenate two 2-dimensional arrays.

In [28]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
ccat = np.concatenate((a,b),1)
print(ccat)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


### 28. Write a Python program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

In [29]:
a = np.arange(1,15)
np.split(a,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

### 29. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.

In [30]:
a = np.arange(16).reshape(4,4)
print(np.hsplit(a,[2,6]))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


### 30. Write a NumPy program to get the number of nonzero elements in an array.

In [31]:
a = np.array([[0,10,20], [20,30,40]])
np.count_nonzero(a)

5

### 31. Write a NumPy program to add an extra column to a NumPy array.

In [32]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100],[200]])
np.append(x,y, axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

### 32. Write a NumPy program to remove the negative values in a NumPy array with 0.

In [33]:
a = np.array([-1,-4,0,2,3,4,5,-6])
a[a<0] =0
print(a)

[0 0 0 2 3 4 5 0]


### 33. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

In [34]:
a = np.array([[1,2,3],[4,5,np.nan],[7,8,9],[1,0,1]])
print('Original array:','\n',a)
print('Array after removing rows with nan:', '\n',a[~np.isnan(a).any(axis=1)])

Original array: 
 [[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Array after removing rows with nan: 
 [[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


### 34. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

In [35]:
a = np.array([97,101,105,111,117])
b = np.array(['a','e','i','o','u'])
i = np.where((a>100) & (a<110))
b[i]

array(['e', 'i'], dtype='<U1')

### 35. Write a NumPy program to count the frequency of unique values in numpy array.

In [36]:
a = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
unique, frequency = np.unique(a, return_counts = True)
print(' Unique values:', unique, '\n','Frequency:', frequency)

 Unique values: [10 20 30 40 50] 
 Frequency: [3 4 2 2 1]


### 36.Write a NumPy program to access last two columns of a multidimensional columns.

In [37]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a[:,[1,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


### 37. Write a NumPy program to find indices of elements equal to zero in a NumPy array.

In [38]:
a = np.array([1,0,2,0,3,0,4,5,6,7,8])
np.where(a==0)

(array([1, 3, 5]),)