## Numpy Assignement - Sri Das

In [1]:
import numpy as np

### 1. Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.


In [2]:
house_size = [100, 300, 250, 618, 150, 412, 190, 290, 115, 275]
house_rooms = [2, 4, 4, 7, 3, 5, 3, 5, 2, 4]
house_price = [90000, 200000, 175000, 700000, 125000, 350000, 150000, 195000, 100000, 185000]

hou_mar = np.array([house_size, house_rooms, house_price])
hou_mar

array([[   100,    300,    250,    618,    150,    412,    190,    290,
           115,    275],
       [     2,      4,      4,      7,      3,      5,      3,      5,
             2,      4],
       [ 90000, 200000, 175000, 700000, 125000, 350000, 150000, 195000,
        100000, 185000]])

### 2. Transpose the array you have created, so that every line can represent features of one house.

In [3]:
houses = np.transpose(hou_mar)
houses

array([[   100,      2,  90000],
       [   300,      4, 200000],
       [   250,      4, 175000],
       [   618,      7, 700000],
       [   150,      3, 125000],
       [   412,      5, 350000],
       [   190,      3, 150000],
       [   290,      5, 195000],
       [   115,      2, 100000],
       [   275,      4, 185000]])

### 3. Display the shape of the array and explain what it means.


In [4]:
houses.shape

(10, 3)

#### The initial array was a 3 x10 matrix, each 'row' was representing one feature of the houses. By transposing we turned it into a 10 X 3 matrix where each row now represents all the features of a single house.

### 4. Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [5]:
from numpy import genfromtxt

In [6]:
earthq = np.genfromtxt('earthquakes1970-2014.csv', delimiter=',')

In [7]:
earthq.shape

(5305, 12)

### 5. Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [25]:
eq_s = earthq[:20, [2,4,5,6,11]]
eq_s.shape

(20, 5)

### 6. Display the row numbers where last values are equal to 4.5 or higher.

In [9]:
np.where(eq_s[:,4] >= 4.5)

(array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 16, 17, 18]),)

### 7. Assign 1 to first row.

In [26]:
eq_s[0, :] = 1
eq_s[0, :]

array([1., 1., 1., 1., 1.])

### 8. Save the final state of the array to disk. You are going to use this in the next assignment.

In [14]:
np.savetxt('earthquakes_sliced.csv', X=eq_s, delimiter=',')

### 9. Load the array you saved in the previous lesson from the disk.

In [40]:
eq_file = np.genfromtxt('earthquakes_sliced.csv', delimiter=',')

### 10. Display the mean and the standard deviation for each column.

In [17]:
print(eq_file.mean(axis=0))

[30.71571  6.065        nan 74.2          nan]


In [18]:
print(eq_file.std(axis=0))

[137.78624508   1.21089843          nan  55.07867101          nan]


### 11. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

In [46]:
num = np.array([1,25,25,10,4])
diff = eq_file - num